[tool.black]
exclude="venv/*"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[mypy]
ignore_missing_imports = true

[tool.pylint.master]
load-plugins ="pylint.extensions.docparams, pylint.extensions.docstyle, pylint.extensions.mccabe"
jobs=4

[tool.pylint.basic]
good-names=["i", "e", "s3", "logger", "pd", "db", "df", "dt"]

[tool.pylint.logging]
logging_format_style = "new"
logging_fstring_interpolation = "no"

[tool.pylint.format]
max-line-length = 88

[tool.pylint.message_control]
disable = ['line-too-long',
           'import-error',
           'docstring-first-line-empty',
           'logging-fstring-interpolation',
           'no-self-use',
           'too-few-public-methods',
           'trailing-whitespace']